name: Update WakaTime Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  update-readme:
    name: Update WakaTime stats
    runs-on: ubuntu-latest

    steps:
      - name: Update WakaTime stats
        uses: AptS-1547/wakatime-readme-updater@v1
        with:
          wakatime_api_key: ${{ secrets.WAKATIME_API_KEY }}
          gh_token: ${{ github.token }}
          repository: ${{ github.repository }}
          readme_path: README.md
          section_name: waka
          stats_range: "7"
          commit_message: "📊 Update WakaTime stats"
